-- Insert remaining 27 prompts (day 2-28, since day 1 already exists)
INSERT INTO public.prompts (text, dimension, day_number, phase, tags) VALUES
('What assumption about the world was challenged today?', 'worldview', 2, 'foundation', '{"assumptions","perspective"}'),
('Describe a meaningful interaction you had today. What made it meaningful?', 'relationships', 3, 'foundation', '{"connection","meaning"}'),
('Describe a moment today when you felt most like yourself. What were you doing?', 'identity', 4, 'foundation', '{"authenticity","self-expression"}'),
('How did your perspective shift from the beginning to the end of today?', 'worldview', 5, 'foundation', '{"perspective","change"}'),
('How did you show up for someone today, even in a small way?', 'relationships', 6, 'foundation', '{"support","presence"}'),
('What strength did you rely on today? How did it serve you?', 'identity', 7, 'foundation', '{"strengths","resilience"}'),
('What did you notice today that you usually overlook?', 'worldview', 8, 'foundation', '{"awareness","mindfulness"}'),
('What did someone teach you today, whether they meant to or not?', 'relationships', 9, 'foundation', '{"learning","insight"}'),
('If you could describe your day in three words that capture who you are, what would they be?', 'identity', 10, 'foundation', '{"self-concept","values"}'),
('Describe something that happened today from two different perspectives.', 'worldview', 11, 'foundation', '{"perspective-taking","empathy"}'),
('Describe a moment when you felt truly heard or understood today.', 'relationships', 12, 'foundation', '{"understanding","connection"}'),
('What part of your identity felt most visible or invisible today?', 'identity', 13, 'foundation', '{"visibility","authenticity"}'),
('What pattern did you notice in your day? What might it mean?', 'worldview', 14, 'foundation', '{"patterns","meaning-making"}'),
('How did you navigate a difference between yourself and someone else today?', 'relationships', 15, 'foundation', '{"conflict","difference"}'),
('What did you say yes to today that aligned with who you want to be?', 'identity', 16, 'foundation', '{"values","alignment"}'),
('What surprised you about today? What does that surprise reveal about your expectations?', 'worldview', 17, 'foundation', '{"expectations","surprise"}'),
('What boundary did you honor (or wish you had honored) today?', 'relationships', 18, 'foundation', '{"boundaries","self-care"}'),
('Describe a choice you made today. What does it reveal about your priorities?', 'identity', 19, 'foundation', '{"choices","priorities"}'),
('If today was a chapter in your life story, what would it be called and why?', 'worldview', 20, 'foundation', '{"narrative","meaning"}'),
('Who made you smile today? What did they do or say?', 'relationships', 21, 'foundation', '{"joy","connection"}'),
('What would you do differently today if you were being completely authentic?', 'identity', 22, 'foundation', '{"authenticity","growth"}'),
('What did you believe was possible today that you did not believe yesterday?', 'worldview', 23, 'foundation', '{"beliefs","possibility"}'),
('How did you contribute to someone else''s day today?', 'relationships', 24, 'foundation', '{"contribution","impact"}'),
('What aspect of yourself are you developing right now? How did it show up today?', 'identity', 25, 'foundation', '{"growth","development"}'),
('What did you pay attention to today? What does that tell you about what matters to you?', 'worldview', 26, 'foundation', '{"attention","values"}'),
('What do you appreciate about the people in your life right now?', 'relationships', 27, 'foundation', '{"gratitude","appreciation"}'),
('How did you make sense of something confusing or uncertain today?', 'worldview', 28, 'foundation', '{"uncertainty","sense-making"}');
