import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

/**
 * GET - Fetch user's certificates
 */
export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { data: certificates, error } = await supabase
      .from('certificates')
      .select('*')
      .eq('user_id', user.id)
      .order('completed_at', { ascending: false });

    if (error) {
      throw error;
    }

    return NextResponse.json({ certificates });
  } catch (error) {
    console.error('Get certificates error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch certificates' },
      { status: 500 }
    );
  }
}

/**
 * POST - Generate certificate for completed course
 * Called automatically when user completes all lessons in a module
 */
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { courseSlug, courseName } = await request.json();

    if (!courseSlug || !courseName) {
      return NextResponse.json(
        { error: 'Course slug and name required' },
        { status: 400 }
      );
    }

    // Verify course is actually complete
    const { data: lessonProgress } = await supabase
      .from('lesson_progress')
      .select('*')
      .eq('user_id', user.id)
      .eq('course_slug', courseSlug)
      .eq('is_completed', true);

    if (!lessonProgress || lessonProgress.length === 0) {
      return NextResponse.json(
        { error: 'No lessons completed for this course' },
        { status: 400 }
      );
    }

    // Get user profile for name
    const { data: profile } = await supabase
      .from('profiles')
      .select('name')
      .eq('id', user.id)
      .single();

    // Create certificate record
    const { data: certificate, error } = await supabase
      .from('certificates')
      .upsert({
        user_id: user.id,
        course_slug: courseSlug,
        course_name: courseName,
        certificate_url: null, // Will be generated by background job
      }, {
        onConflict: 'user_id,course_slug'
      })
      .select()
      .single();

    if (error) {
      throw error;
    }

    // TODO: Trigger certificate PDF generation
    // Options:
    // 1. Generate on-demand when user views certificate
    // 2. Queue background job to generate PDF
    // 3. Use service like PDF.co or CloudConvert

    return NextResponse.json({
      success: true,
      certificate,
      message: `Certificate earned for ${courseName}!`
    });
  } catch (error) {
    console.error('Generate certificate error:', error);
    return NextResponse.json(
      { error: 'Failed to generate certificate' },
      { status: 500 }
    );
  }
}
